Update deploy.yaml

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -24,7 +24,13 @@ jobs:
           wget https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_export_templates.tpz -O 4.3.stable.tpz
           mkdir -p ~/.local/share/godot/export_templates
           unzip 4.3.stable.tpz -d ~/.local/share/godot/export_templates
-          mv ~/.local/share/godot/export_templates/templates ~/.local/share/godot/export_templates/4.3.stable
+          # Verify the contents and move the templates folder
+          if [ -d ~/.local/share/godot/export_templates/templates ]; then
+            mv ~/.local/share/godot/export_templates/templates ~/.local/share/godot/export_templates/4.3.stable
+          else
+            echo "Error: 'templates' folder not found after extraction"
+            exit 1
+          fi
       - name: Export game
         run: |
           ~/godot/Godot_v4.3-stable_linux.x86_64 --headless --export-release "Web" ./build/html/LD56.html
